### ISSUE TITLE
Nest 10 do not support ESM, do I need this pacakge?

### ISSUE THREAD

**Issue by gustawdaniel** [antongolub/nestjs-esm-fix#2]
Context:

There is an open PR for ESM in Nest https://github.com/nestjs/nest/pull/8736
Probably will not be merged in a predictable time horizon.

In the README of this package, there is info, that this is a temporary solution for the nest 9.
Should I use it now, or there are other more recommended approaches?

**Comment by antongolub** [comment]
@gustawdaniel,

I'm afraid haven't tested nestjs@10 case. I'll add a notice.

> other more recommended approaches.   

I wish I knew, sorry. I'm just keeping an eye on [the issues](https://github.com/search?q=org%3Anestjs+esm&type=issues). The last responses [are not optimistic](https://github.com/nestjs/nest/issues/11897), alas
